---
abstract: 'Statically check for named methods'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  B::Hooks::OP::Check: 0
  B::Hooks::OP::PPAddr: 0
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Methods-CheckNames
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::OP::Check: 0
  B::Hooks::OP::PPAddr: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05_01
